;***************************************************************************
;
;	    Filename: I2CSlave.ASM
;	    Date: 09/30/2024
;	    File Version: 1
;	    Author: Owen Fujii
;	    Company: Idaho State University
;	    Description: A Program for a slave I2C device that controls
;			 servo motors using PWM 
;**************************************************************************
	
;*************************************************************************
; 
;	    Revision History:
;   
;	    Modified as listed
;	    Started 10/23/2024-10/24/2024
;
;*************************************************************************
    
    ; PIC16F1788 Configuration Bit Settings

; Assembly source line config statements

	#include "p16f1788.inc"
	#include "1788Setup.inc"
	#include "1788POPout.inc"
	#include "1788Pushin.inc"

; CONFIG1
; __config 0xE9A4
 __CONFIG _CONFIG1, _FOSC_INTOSC & _WDTE_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOREN_OFF & _CLKOUTEN_OFF & _IESO_OFF & _FCMEN_ON
; CONFIG2
; __config 0xDFFF
 __CONFIG _CONFIG2, _WRT_OFF & _VCAPEN_OFF & _PLLEN_ON & _STVREN_ON & _BORV_LO & _LPBOR_OFF & _LVP_OFF

 
 ;*********************
 ;Define Constants
 ;*********************
 
    ANSELECT EQU H'031'
    TEMP     EQU H'032'
 

    ORG H'000'					
    GOTO SETUP					;RESET CONDITION GOTO SETUP
    ORG H'004'
    GOTO INTER
    
TABLE
    ADDWF PCL,1	    ; TABLE OF VALUES FOR CCPXL
    RETLW H'008'
    RETLW H'00A'
    RETLW H'00B'
    RETLW H'00E'
    RETLW H'00F'
    RETLW H'010'
    RETLW H'011'
    RETLW H'013'
    RETLW H'014'
    RETLW H'015'
    RETLW H'016'
    RETLW H'017'
    RETLW H'018'
    RETLW H'019'
    RETLW H'01A'
    RETLW H'01B'
    RETLW H'01C'
    RETLW H'01D'
    RETLW H'01E'
    RETLW H'020'
    
TABLETWO
    ADDWF PCL,1	    ; TABLE OF VALUES FOR CCPXCON
    RETLW H'02C'
    RETLW H'03C'
    RETLW H'00C'
    RETLW H'01C'
    RETLW H'02C'
    RETLW H'03C'
    RETLW H'00C'
    RETLW H'01C'
    RETLW H'02C'
    RETLW H'03C'
    RETLW H'00C'
    RETLW H'01C'
    RETLW H'02C'
    RETLW H'03C'
    RETLW H'00C'
    RETLW H'01C'
    RETLW H'02C'
    RETLW H'02C'
    RETLW H'03C'
    RETLW H'00C'
    
    
SETUP
    BANKSEL OSCCON
    MOVLW H'06B'	    ; SET 1MHZ INTERNAL OSSCILATOR
    MOVWF OSCCON
    BANKSEL OSCSTAT
    BTFSC OSCSTAT,OSTS	    ; WAIT FOR OSSCILATOR TO BE READY
    GOTO $-1
    CALL START		    ; CALL SETUP INCLUDE
    BANKSEL SSP1CON1
    MOVLW H'036'	    ; SET 7 BIT SLAVE I2C
    MOVWF SSP1CON1
    BANKSEL SSP1ADD
    MOVLW H'040'	    ; SET SLAVE ADDRESS
    MOVWF SSP1ADD
    BANKSEL SSP1CON2
    BSF SSP1CON2,SEN	    ; ENABLE CLOCK STRETCH
    BANKSEL SSP1CON3
    CLRF SSP1CON3
    BSF SSP1CON3,AHEN	    ; ENABLE CLOCK STRETCH FOR ADDRESS AND DATA
    BSF SSP1CON3,DHEN
    BANKSEL PR2		    ; SET UP PWM RESOLUTION // 10BIT
    MOVLW H'0FF'
    MOVWF PR2
    BANKSEL T2CON	    ; CONFIGURE TMR2
    MOVLW H'07B'
    MOVWF T2CON
    BANKSEL CCP1CON	    ; SET PWM OUTPUT
    BSF CCP1CON,5	    ; SET LSB1
    BSF CCP1CON,4	    ; SET LSB0
    BSF CCP1CON,3	    ; SET PWM MODE
    BSF CCP1CON,2
    BANKSEL CCPR1L	    ; LOAD UPPER MSBs FOR MIN PW
    MOVLW H'007'
    MOVWF CCPR1L
    BANKSEL APFCON1
    CLRF APFCON1
    BSF APFCON1,6	    ; SET CCP1 TO RB0
    BSF APFCON1,0	    ; SET CCP2 TO RB3
    BANKSEL APFCON2
    CLRF APFCON2
    BSF APFCON2,0	    ; SET CCP3 TO RB5
    BANKSEL T2CON
    BSF T2CON,2		    ; ENABLE PWM
    BANKSEL PIE1
    BSF PIE1,3	    ; ENABLE MSSP INTERRUPT
    BANKSEL INTCON
    CLRF TEMP		    ; CLEAR GPRS
    CLRF ANSELECT
    BSF INTCON,GIE	    ; ENABLE INTERRUPTS
    BSF INTCON,PEIE
    GOTO MAIN

MAIN
    NOP
    BANKSEL PORTB
    BSF PORTB,2
    CALL CHANGEOUT	    ; CHECK IF RECIEVED DATA HAS ACTION
    GOTO MAIN
    
INTER
    BANKSEL INTCON
    CLRF INTCON
    CALL PUSHIN
    BCF PORTB,2
    BANKSEL PIR1
    BTFSC PIR1,SSP1IF	    ; CHECK MSSP INTERRUPT FLAG
    CALL RECIEVE	
    BANKSEL INTCON
    BSF INTCON,GIE
    BSF INTCON,PEIE
    CALL POPOUT
    RETFIE
    
RECIEVE
    BANKSEL PIR1
    CLRF PIR1		; CLEAR FLAG
    BCF PORTB,2
    BANKSEL SSP1BUF 
    MOVF SSP1BUF,0	; READ RECIEVED DATA
    BANKSEL PORTB
    BTFSC TEMP,0	; CHECK IF THIS IS DATA OR ADDRESS
    MOVWF ANSELECT
    BSF TEMP,0
    BANKSEL SSP1CON1	
    BSF SSP1CON1,CKP	; RELEASE CLOCK LINE
    RETURN
    
    
CHANGEOUT    
    BCF PORTB,1
    CLRF TEMP
    BTFSC ANSELECT,0	; CHECK IF SERVO 1 DATA SELECTED
    GOTO SETCCP1
    BTFSC ANSELECT,1	; CHECK IF SERVO 2 DATA SELECTED
    GOTO SETCCP2
    BTFSC ANSELECT,2	; CHECK IF SERVO 3 DATA SELECTED
    GOTO SETCCP3
   ; BCF PORTB,2
    RETURN
    
SETCCP1
    BANKSEL T2CON
    BCF T2CON,2		    ; DISABLE TMR2
    BANKSEL TRISB
    BSF TRISB,0		    ; SET CORRESPONDING TRIS
    BANKSEL PORTB
    RRF ANSELECT,1	    ; ROTATE RIGHT THROUGH CARRY 3X
    RRF ANSELECT,1
    RRF ANSELECT,1
    BCF ANSELECT,7	    ; CLEAR UPPER 3 BITS
    BCF ANSELECT,6
    BCF ANSELECT,5
    MOVF ANSELECT,0
    BANKSEL CCP1CON
    CALL TABLETWO	    ; CALL TABLE VALUE
    MOVWF CCP1CON
    BANKSEL T2CON
    MOVF ANSELECT,0
    BANKSEL CCPR1L
    CALL TABLE		    ; CALL TABLE VALUE
    MOVWF CCPR1L
    BANKSEL T2CON
    BSF T2CON,2		    ; ENABLE TMR2
    BTFSC PIR1,2	    ; WAIT FOR ROLLOVER
    GOTO $-1
    CLRF ANSELECT
    BANKSEL TRISB	    ; CLEAR TRIS TO REENABLE
    BCF TRISB,0
    RETURN
    ; REPEAT FOR EACH CCPX OUTPUT
SETCCP2
    BANKSEL T2CON
    BCF T2CON,2
    BANKSEL TRISB
    BSF TRISB,0
    BANKSEL PORTB
    RRF ANSELECT,1
    RRF ANSELECT,1
    RRF ANSELECT,1
    BCF ANSELECT,7
    BCF ANSELECT,6
    BCF ANSELECT,5
    MOVF ANSELECT,0
    BANKSEL CCP2CON
    CALL TABLETWO
    MOVWF CCP2CON
    BANKSEL T2CON
    MOVF ANSELECT,0
    BANKSEL CCPR2L
    CALL TABLE
    MOVWF CCPR2L
    BANKSEL T2CON
    BSF T2CON,2
    BTFSC PIR1,2
    GOTO $-1
    CLRF ANSELECT
    BANKSEL TRISB
    BCF TRISB,0
    RETURN
    
SETCCP3
    BANKSEL T2CON
    BCF T2CON,2
    BANKSEL TRISB
    BSF TRISB,0
    BANKSEL PORTB
    RRF ANSELECT,1
    RRF ANSELECT,1
    RRF ANSELECT,1
    BCF ANSELECT,7
    BCF ANSELECT,6
    BCF ANSELECT,5
    MOVF ANSELECT,0
    BANKSEL CCP3CON
    CALL TABLETWO
    MOVWF CCP3CON
    BANKSEL T2CON
    MOVF ANSELECT,0
    BANKSEL CCPR3L
    CALL TABLE
    MOVWF CCPR3L
    BANKSEL T2CON
    BSF T2CON,2
    BTFSC PIR1,2
    GOTO $-1
    CLRF ANSELECT
    BANKSEL TRISB
    BCF TRISB,0
    RETURN
 
END