;***************************************************************************
;
;	    Filename: Traffic Light.asm
;	    Date: 09/30/2024
;	    File Version: 1
;	    Author: Owen Fujii
;	    Company: Idaho State University
;	    Description: A program that simulates a traffic intersection 
;
;*************************************************************************
	
;*************************************************************************
; 
;	    Revision History:
;   
;	    Modified as listed
;	    Started 09/30/2024 
;
;*************************************************************************

    	;Basic Setup File for the PIC16F883

		#INCLUDE <p16f883.inc>        		; processor specific variable definitions
		#INCLUDE <TrafficSetup.inc>
		#INCLUDE <POPout.inc>
		#INCLUDE <PUSHin.inc>
		LIST      p=16f883		  	; list directive to define processor
		errorlevel -302,-207,-305,-206,-203	;suppress "not in bank 0" message,  Found label after column 1,
							;Using default destination of 1 (file),  Found call to macro in column 1

		#include "p16f883.inc"

; CONFIG1
; __config 0xF8E7
 __CONFIG _CONFIG1, _FOSC_XT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
;******************************************		
;Define Constants
;******************************************

#Define 	BAUD		D'100'				;Desired Baud Rate in Kbps for I2C
#Define		FOSC		D'16000'			;Oscillator Clock in KHz This must be filled
 
	    COMPARECNT EQU H'22'
	    STORAGECNT EQU H'23'
	    QUEUE      EQU H'24'
	    BOTH       EQU H'25'
	    HOLDDELAY  EQU H'26'
	    
 
 ; GPR 20 and 21 are used for interrupt save
 
		ORG H'000'					
		GOTO SETUP					;RESET CONDITION GOTO SETUP
		ORG H'004'
		GOTO INTER
 
 SETUP
	CALL START
	BANKSEL PORTC
	MOVLW H'0C'
	MOVWF PORTC
	CALL TMRSTART	
	CLRF QUEUE
	CLRF STORAGECNT
	GOTO MAIN
	
MAIN
	NOP
	GOTO MAIN
	
TMRSTART
	BCF STATUS,RP0
	CLRF INTCON	    ; CLEAR ALL REGISTERS ASSOCIATED WITH TMR RESET.
	CLRF T2CON
	BSF STATUS, RP0
	CLRF PIE1
	CLRF PR2
	MOVLW H'FF'
	MOVWF PR2
	BCF STATUS, RP0
	CLRF PIR1
	CLRF TMR2
	CALL TMRGREEN
	MOVLW H'7A'
	MOVWF T2CON
	BANKSEL PIE1
	BSF PIE1,1          ; ENABLE TMR1 INTERRUPT
	BANKSEL INTCON
	MOVLW H'C8'	    ; ENABLE GLOBAL AND PERIPHERAL INTERRUPTS AND PORTB INT
	MOVWF INTCON
	BSF T2CON,2	    ; START TMR1
	RETURN
	

OVERFLOWCHECK
	BANKSEL INTCON
	BCF STATUS,0
	INCF STORAGECNT,1
	MOVF COMPARECNT,0
	ADDWF STORAGECNT,0
	BTFSC STATUS,0
	CALL SWITCHER
	BCF PIR1,1
	CALL POPOUT
	RETFIE
	
SWITCHER
	BANKSEL PORTC
	CLRF STORAGECNT
	BCF STATUS,0
	BTFSC PORTC,RC2  ; SET FOR RC2
	GOTO SETYELLOWNORTH
	BTFSC PORTC,RC1  ; SET FOR RC1 
	GOTO SETGREENEAST
	BTFSC PORTC,RC5	; SET FOR RC5 
	GOTO SETYELLOWEAST
	BTFSC PORTC,RC4	; SET FOR RC4
	GOTO SETGREENNORTH
	RETURN
	
SETYELLOWNORTH
	BTFSC QUEUE,1
	GOTO SKIPP
	BTFSC QUEUE,0
	GOTO SETGREENNORTH
SKIPP
	MOVLW H'0A'
	MOVWF PORTC
	CALL TMRYELLOW
	RETURN
SETGREENEAST
	MOVLW H'21'
	MOVWF PORTC
	CLRF QUEUE
	CALL TMRGREEN
	RETURN
SETYELLOWEAST
	BTFSC QUEUE,0
	GOTO SKIP
	BTFSC QUEUE,1
	GOTO SETGREENEAST
SKIP
	MOVLW H'11'
	MOVWF PORTC
	CALL TMRYELLOW
	RETURN
	
SETGREENNORTH
	MOVLW H'0C'
	MOVWF PORTC
	CLRF QUEUE
	CALL TMRGREEN
	RETURN
	
TMRYELLOW
	CLRF COMPARECNT
	MOVLW H'F0'         ; SET OVERFLOW COMPARE GPR COMPLEMENT OF FINAL COUNT PLUS ONE WAS FC
	MOVWF COMPARECNT
	RETURN

TMRGREEN
	CLRF COMPARECNT
	MOVLW H'B3'        ; SET OVERFLOW COMPARE GPR COMPLEMENT OF FINAL COUNT PLUS ONE WAS ED FOR TMR1
	MOVWF COMPARECNT
	RETURN
	
INTER
	CALL PUSHIN
	BANKSEL PIR1
	BTFSC PIR1,1
	GOTO OVERFLOWCHECK
	BTFSC INTCON,0
	GOTO INTERSECTION	
	CALL POPOUT
	RETFIE
	
INTERSECTION
	BANKSEL PORTB
	CLRF INTCON
	BTFSC PORTB,0	; CHECK RB0
	BSF QUEUE,0
	BSF PORTC,7
	BTFSC PORTB,1   ; CHECK RB1
	BSF QUEUE,1
	MOVLW H'C8'
	MOVWF INTCON
	CALL POPOUT
	RETFIE
	
	
END