;***************************************************************************
;
;	    Filename: EEPROM.ASM
;	    Date: 09/30/2024
;	    File Version: 1
;	    Author: Owen Fujii
;	    Company: Idaho State University
;	    Description: A Program that saves keypresses to EEPROM
;
;*************************************************************************
	
;*************************************************************************
; 
;	    Revision History:
;   
;	    Modified as listed
;	    Started 10/23/2024-10/24/2024
;
;*************************************************************************

    	;Basic Setup File for the PIC16F883

		#INCLUDE <p16f883.inc>        		; processor specific variable definitions
		#INCLUDE <Setup.inc>
		#INCLUDE <POPout.inc>
		#INCLUDE <PUSHin.inc>
		#INCLUDE <EEWRITE.inc>
		#INCLUDE <EEREAD.inc>
		LIST      p=16f883		  	; list directive to define processor
		errorlevel -302,-207,-305,-206,-203	;suppress "not in bank 0" message,  Found label after column 1,
							;Using default destination of 1 (file),  Found call to macro in column 1

		#include "p16f883.inc"

; CONFIG1
; __config 0xF8E7
 __CONFIG _CONFIG1, _FOSC_XT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
;******************************************		
;Define Constants
;******************************************

#Define 	BAUD		D'100'				;Desired Baud Rate in Kbps for I2C
#Define		FOSC		D'16000'			;Oscillator Clock in KHz This must be filled

	RESTEP	    EQU H'22'
	STORECNT    EQU H'23'
	COUNTER     EQU H'24'
	NULL        EQU H'25'
	COMPARE	    EQU H'26'
	MXCNT	    EQU H'27'
	TEMP	    EQU H'28'
	TMR2SAVE    EQU H'29'
	TMR0SAVE    EQU H'30'
	    


	ORG H'000'					
	GOTO SETUP					;RESET CONDITION GOTO SETUP
	ORG H'004'
	GOTO INTER

SETUP
	CALL START
	BANKSEL EEDATH		; CLEAR UPPER BITS OF EE DATA AND ADDRESS
	CLRF EEDATH
	BANKSEL EEADRH 
	CLRF EEADRH
	BANKSEL INTCON
	CLRF RESTEP		; CLEAR GPRS
	CLRF STORECNT
	CLRF COUNTER
	CLRF NULL
	CLRF COMPARE
	CLRF MXCNT
	MOVLW H'0A'		; SET MAXIMUM RECORD COUNT
	MOVWF MXCNT
	BSF INTCON,7		; ENABLE INTERRUPTS
	BSF INTCON,6		
	BSF INTCON,3
	GOTO HOLD
	
HOLD
	BANKSEL PORTC		; WAIT FOR NEXT OPERTATION 
	CLRF PORTC
	MOVLW H'53'		; CYCLE BETWEEN A "S" AND "0"
	MOVWF PORTC
	MOVLW H'88'
	MOVWF INTCON
	CALL DELAY
	MOVLW H'30'
	MOVWF PORTC
	CALL DELAY
	CLRF COUNTER
	GOTO HOLD
	
DELAY
	CLRF TMR2	    ; APPROXIMATELY ONE SECOND SOFTWARE DELAY
LOOP2
	CLRF TMR0
LOOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	DECFSZ TMR0
	GOTO LOOP
	DECFSZ TMR2
	GOTO LOOP2
	MOVLW H'FC'
	MOVWF TMR0
LOOP3
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	DECFSZ TMR0
	GOTO LOOP3
	RETURN
		
	
REPLAY
	BCF STATUS,RP0
	BCF INTCON,7	    ; DISABLE INTERRUPTS
	MOVLW H'5E'	    ; ACK ENTERING REPLAY
	MOVWF PORTC
	CALL DELAY	   
	MOVLW H'0B'        ; MOVE REPLAY COUNT GPR
	CALL EEREAD
	BANKSEL PORTC
	MOVWF RESTEP	    ; MOVE THE BUTTON COUNT INTO CNT REGISTER
	BCF STATUS,Z
	SUBWF NULL,0	    ; DO NOT REPLAY IF NO COUNT WAS SAVED
	BTFSC STATUS,Z
	RETURN
	CLRF COMPARE
	CALL DELAY
FOLLOW	
	MOVF COMPARE,0	    ; LOOP UNTIL ALL NUMBERS HAVE BEEN DISPLAYED
	BCF STATUS,Z
	SUBWF RESTEP,0
	BTFSC STATUS,Z
	RETURN
	MOVF COMPARE,0
	CALL EEREAD
	BANKSEL PORTC
	MOVWF PORTC
	CALL DELAY
	INCF COMPARE,1
	GOTO FOLLOW

	  
MAIN	
	BANKSEL PORTC 
	BCF INTCON,7	; DISABLE INTERRUPTS
	BCF INTCON,3
	MOVLW H'23'	; DISPLAY A #             
	MOVWF PORTC                                                           
	GOTO RUN
RUN 
	BANKSEL PORTC
	MOVF COUNTER,0
	BCF STATUS,Z
	SUBWF MXCNT,0		; CHECK IF MAX COUNT HAS BEEN REACHED
	BTFSC STATUS,Z
	GOTO STOP		
	BTFSC PORTB,2
        GOTO STOP		; POLL THE STOP BUTTON
	BANKSEL PORTA
	MOVF COUNTER,0
	BANKSEL EEADR
	MOVWF EEADR
	BANKSEL PORTA
				 
	CLRF PORTB	; MODIFIED VERSION OF KEYPAD PROGRAM. 	
	BSF PORTB,4	; OUTPUTS ARE THE UPPER NIBBLE OF PORTB		    	
	BTFSS PORTA,0   ; INPUTS ARE THE LOWER NIBBLE OF PORTA                    
	GOTO $+3	; THIS KEYPAD USES A MORE COMPACT STRUCTURE 
	MOVLW H'30'	; REDUCES THE OVERALL CODE NEEDED FOR PROGRAM 
	GOTO WRITEPROM
	BTFSS PORTA,1
	GOTO $+3
	MOVLW H'31'
	GOTO WRITEPROM
	BTFSS PORTA,2
	GOTO $+3
	MOVLW H'32'
	GOTO WRITEPROM
	BTFSS PORTA,3
	GOTO $+3
	MOVLW H'33'
	GOTO WRITEPROM                           
	BCF PORTB,4	                     


	BSF PORTB,5                        
	BTFSS PORTA,0                        
	GOTO $+3
	MOVLW H'34'
	GOTO WRITEPROM
	BTFSS PORTA,1
	GOTO $+3
	MOVLW H'35'
	GOTO WRITEPROM
	BTFSS PORTA,2
	GOTO $+3
	MOVLW H'36'
	GOTO WRITEPROM
	BTFSS PORTA,3
	GOTO $+3
	MOVLW H'37'
	GOTO WRITEPROM                         
	BCF PORTB,5                     

	BSF PORTB,6                         
	BTFSS PORTA,0                      
	
	GOTO $+3
	MOVLW H'38'
	GOTO WRITEPROM
	BTFSS PORTA,1
	
	GOTO $+3
	MOVLW H'39'
	GOTO WRITEPROM
	BTFSS PORTA,2
	GOTO $+3
	MOVLW H'41'
	GOTO WRITEPROM
	BTFSS PORTA,3
	GOTO $+3
	MOVLW H'42'
	GOTO WRITEPROM
	BCF PORTB,6				
	BSF PORTB,7				
	BTFSS PORTA,0				
	GOTO $+3
	MOVLW H'43'
	GOTO WRITEPROM
	BTFSS PORTA,1
	GOTO $+3
	MOVLW H'44'
	GOTO WRITEPROM
	BTFSS PORTA,2
	GOTO $+3
	MOVLW H'45'
	GOTO WRITEPROM
	BTFSS PORTA,3
	GOTO $+3
	MOVLW H'46'
	GOTO WRITEPROM
	BCF PORTB,7
	GOTO MAIN	; IF NO BITS ARE SET RETURN TO MAIN TO SET #


WRITEPROM
	BANKSEL PORTA	    ; MOVE WORKING TO DISPLAY
	MOVWF PORTC
	BANKSEL EEDATA
	MOVWF EEDATA	    ; MOVE INTO EEPROM DATA
	BANKSEL EECON1
	BCF EECON1,EEPGD 
	CALL EEWRITE	    ; CALL EEPROM WRITE INCLUDE FILE
	BANKSEL PORTC
	INCF COUNTER,1	    ; INDICATE SUCCESSFUL WRITE
	CALL DELAY	    ; DELAY TO PREVENT FAST TOGGLING
	GOTO MAIN
	


INTER
	BCF STATUS,RP0
	CALL PUSHIN
	BCF INTCON,7	
	MOVF PORTC,0	    ; SAVE ALL CURRENT STATES
	MOVWF TEMP
	MOVF TMR2,0
	MOVWF TMR2SAVE
	MOVF TMR0,0
	MOVWF TMR0SAVE
	BTFSC INTCON,0
	CALL PORTCHECK	    ; CHECK FOR PORTB INTERRUPT
	BANKSEL INTCON
	CLRF INTCON
	MOVF TMR2SAVE,0	    ; RETURN PRIOR STATE
	MOVWF TMR2
	MOVF TMR0SAVE,0
	MOVWF TMR0
	MOVF TEMP,0
	MOVWF PORTC
	BSF INTCON,7	    ; REENABLE INTERRUPTS
	BSF INTCON,3
	CALL POPOUT
	RETFIE


PORTCHECK
	BANKSEL PORTB
	BTFSC PORTB,0
	CALL MAIN	    ; GOTO KEYPAD CODE
	BTFSC PORTB,1
	CALL REPLAY	    ; GOTO REPLAY CODE
	RETURN

STOP
	BANKSEL PORTA
	MOVLW H'0B'	    ; WRITE TO FIXED ADDRESS
	BANKSEL EEADR
	MOVWF EEADR
	BANKSEL PORTC
	MOVF COUNTER,0	    ; SAVE # OF KEYPRESSES
	BANKSEL EEDATA
	MOVWF EEDATA
	CALL EEWRITE	    ; WRITE
	RETURN
	

END